export const ROMA_VARIATIONS: Record<string, string[]> = {
  a: ["a"],
  i: ["i"],
  u: ["u"],
  e: ["e"],
  o: ["o"],
  ka: ["ka"],
  ki: ["ki"],
  ku: ["ku"],
  ke: ["ke"],
  ko: ["ko"],
  sa: ["sa"],
  si: ["si"],
  su: ["su"],
  se: ["se"],
  so: ["so"],
  ta: ["ta"],
  ti: ["ti"],
  tu: ["tu"],
  te: ["te"],
  to: ["to"],
  na: ["na"],
  ni: ["ni"],
  nu: ["nu"],
  ne: ["ne"],
  no: ["no"],
  ha: ["ha"],
  hi: ["hi"],
  hu: ["hu"],
  he: ["he"],
  ho: ["ho"],
  ma: ["ma"],
  mi: ["mi"],
  mu: ["mu"],
  me: ["me"],
  mo: ["mo"],
  ya: ["ya"],
  yu: ["yu"],
  yo: ["yo"],
  ra: ["ra"],
  ri: ["ri"],
  ru: ["ru"],
  re: ["re"],
  ro: ["ro"],
  wa: ["wa"],
  wo: ["wo"],
  n: ["n", "nn"],
  ga: ["ga"],
  gi: ["gi"],
  gu: ["gu"],
  ge: ["ge"],
  go: ["go"],
  za: ["za"],
  ji: ["ji"],
  zu: ["zu"],
  ze: ["ze"],
  zo: ["zo"],
  da: ["da"],
  di: ["di"],
  du: ["du"],
  de: ["de"],
  do: ["do"],
  ba: ["ba"],
  bi: ["bi"],
  bu: ["bu"],
  be: ["be"],
  bo: ["bo"],
  pa: ["pa"],
  pi: ["pi"],
  pu: ["pu"],
  pe: ["pe"],
  po: ["po"],
  la: ["la"],
  li: ["li"],
  lu: ["lu"],
  le: ["le"],
  lo: ["lo"],
  ltu: ["ltu"],
  lya: ["lya"],
  lyu: ["lyu"],
  lyo: ["lyo"],
  "-": ["-"],
  "、": [","],
  "。": ["."],
  "!": ["Shift+1"],
  "?": ["Shift+/"],
};

export const GROUP_CONFIG = [
  {
    id: "basic",
    title: "基本 (Basic)",
    rows: [
      {
        chars: ["あ", "い", "う", "え", "お"],
        keys: ["a", "i", "u", "e", "o"],
      },
      {
        chars: ["か", "き", "く", "け", "こ"],
        keys: ["ka", "ki", "ku", "ke", "ko"],
      },
      {
        chars: ["さ", "し", "す", "せ", "そ"],
        keys: ["sa", "si", "su", "se", "so"],
      },
      {
        chars: ["た", "ち", "つ", "て", "と"],
        keys: ["ta", "ti", "tu", "te", "to"],
      },
      {
        chars: ["な", "に", "ぬ", "ね", "の"],
        keys: ["na", "ni", "nu", "ne", "no"],
      },
      {
        chars: ["は", "ひ", "ふ", "へ", "ほ"],
        keys: ["ha", "hi", "hu", "he", "ho"],
      },
      {
        chars: ["ま", "み", "む", "め", "も"],
        keys: ["ma", "mi", "mu", "me", "mo"],
      },
      {
        chars: ["や", "ゆ", "よ", "わ", "ん"],
        keys: ["ya", "yu", "yo", "wa", "n"],
      },
      {
        chars: ["ら", "り", "る", "れ", "ろ"],
        keys: ["ra", "ri", "ru", "re", "ro"],
      },
    ],
  },
  {
    id: "dakuon",
    title: "濁音 (Dakuon)",
    rows: [
      {
        chars: ["が", "ぎ", "ぐ", "げ", "ご"],
        keys: ["ga", "gi", "gu", "ge", "go"],
      },
      {
        chars: ["ざ", "じ", "ず", "ぜ", "ぞ"],
        keys: ["za", "ji", "zu", "ze", "zo"],
      },
      {
        chars: ["だ", "ぢ", "づ", "で", "ど"],
        keys: ["da", "di", "du", "de", "do"],
      },
      {
        chars: ["ば", "び", "ぶ", "べ", "ぼ"],
        keys: ["ba", "bi", "bu", "be", "bo"],
      },
      {
        chars: ["ぱ", "ぴ", "ぷ", "ぺ", "ぽ"],
        keys: ["pa", "pi", "pu", "pe", "po"],
      },
    ],
  },
  {
    id: "yoon",
    title: "拗音 (Yoon)",
    rows: [
      { chars: ["きゃ", "きゅ", "きょ"], keys: ["kya", "kyu", "kyo"] },
      { chars: ["しゃ", "しゅ", "しょ"], keys: ["sya", "syu", "syo"] },
      { chars: ["ちゃ", "ちゅ", "ちょ"], keys: ["tya", "tyu", "tyo"] },
      { chars: ["にゃ", "にゅ", "にょ"], keys: ["nya", "nyu", "nyo"] },
      { chars: ["ひゃ", "ひゅ", "ひょ"], keys: ["hya", "hyu", "hyo"] },
      { chars: ["みゃ", "みゅ", "みょ"], keys: ["mya", "myu", "myo"] },
      { chars: ["りゃ", "りゅ", "りょ"], keys: ["rya", "ryu", "ryo"] },
      { chars: ["ぎゃ", "ぎゅ", "ぎょ"], keys: ["gya", "gyu", "gyo"] },
      { chars: ["じゃ", "じゅ", "じょ"], keys: ["ja", "ju", "jo"] },
      { chars: ["びゃ", "びゅ", "びょ"], keys: ["bya", "byu", "byo"] },
      { chars: ["ぴゃ", "ぴゅ", "ぴょ"], keys: ["pya", "pyu", "pyo"] },
    ],
  },
  {
    id: "symbols",
    title: "小書き・記号",
    rows: [
      {
        chars: ["ぁ", "ぃ", "ぅ", "ぇ", "ぉ"],
        keys: ["la", "li", "lu", "le", "lo"],
      },
      {
        chars: ["っ", "ゃ", "ゅ", "ょ", "ー"],
        keys: ["ltu", "lya", "lyu", "lyo", "-"],
      },
      { chars: ["、", "。", "！", "？"], keys: ["、", "。", "!", "?"] },
    ],
  },
];